name: tracking
channels:
    - main
dependencies:
    - cmake
    - ffmpeg
    - python
    - m2-filesystem         # [win]
    - m2w64-pkg-config      # [win]
    - jom                   # [win]
    - git
