{% set version = environ.get('GIT_DESCRIBE_TAG', '-failed')[1:] %}
{% set number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}
{% set hash = environ.get('GIT_DESCRIBE_HASH', '0') %}

package:
  name: test_python
  version: "{{ version }}"

channels:
  - conda-forge [arm64 or linux]
  - apple [arm64]
  - nodefaults [arm64]
source:
    git_url: https://github.com/mooch443/commons.git
    git_depth: 1
    git_rev: locusts

build:
    script_env:
      - GITHUB_WORKFLOW
    number: 26
    string: "{{ hash }}_{{ number }}"
    run_exports:
        - {{ pin_compatible('python', min_pin='x.x.x', max_pin='x.x.x') }}
        - {{ pin_compatible('libgcc-ng', min_pin='x.x.x', max_pin='x.x.x') }} # [linux]
        - {{ pin_compatible('libstdcxx-ng', min_pin='x.x.x', max_pin='x.x.x') }} # [linux]
    detect_binary_files_with_prefix: True
    files_with_prefix:
        - bin/test_python
    
requirements:
  build:
    - m2-filesystem         # [win]
    - m2w64-pkg-config      # [win]
    - pkg-config            # [not win]
    - jom                   # [win]
    - make                  # [unix]
    - sysroot_linux-64 ==2.17 # [linux]
    - python =3.9 # [win]
    - python =3.9 # [arm64]
    - python ==3.7.11 # [not win and not arm64]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.14
    - git
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxcursor-devel') }}           # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('libXfixes-devel') }}             # [linux]
    - {{ cdt('libXxf86vm') }}            # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxinerama-devel') }}         # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxcursor-devel') }}           # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libselinux') }}            # [linux]
    - {{ cdt('libXdamage-devel') }}            # [linux]
    - {{ cdt('libXau-devel') }}                # [linux]
    - {{ cdt('libuuid-devel') }} # [linux]

  host:
    - pthread-stubs  # [linux]
    - ffmpeg =4
    - python ==3.7.11 # [not win and not arm64]
    - python =3.9 # [osx and arm64]
    - python =3.9 # [win]
    
  run:
    - tensorflow =2.6 # [not linux and not arm64 and not osx]
    - tensorflow-gpu =2.4 # [linux]
    - tensorflow =2   # [osx and not arm64]
    - cudatoolkit # [win]
    - cudnn # [win]
    - scikit-learn
    - grpcio # [arm64]
    - wrapt >=1.11.0 # [arm64]
    - ffmpeg =4
    - numpy
    - python =3.9 # [osx and arm64]
    - python =3.9 # [win]
    - python ==3.7.11 # [not win and not arm64]
    - h5py # [arm64]
    - hdf5 # [arm64]
    - pip  # [arm64]
    - keras-preprocessing # [arm64]
    - requests # [osx and not arm64]
    - six # [osx and not amd64]
    - wheel # [osx and not amd64]
    - requests

about:
  home: https://trex.run
  license: GPLv3
  summary: TRex
  description: >
    This is a test package for testing basic functionality of the commons package.
  doc_url: https://trex.run/docs
  dev_url: https://github.com/mooch443/commons.git
