set(COMMONS_PUBLIC_HEADERS
    types.h
    misc/Base64.h
    misc/Blob.h
    misc/Buffers.h
    misc/CTCollection.h
    misc/CallbackManager.h
    misc/CircularGraph.h
    misc/CommandLine.h
    misc/CropOffsets.h
    misc/Deprecations.h
    misc/DisplayValue.h
    misc/EnumClass.h
    misc/FormatColor.h
    misc/GlobalSettings.h
    misc/Grid.h
    misc/IllegalVector.h
    misc/Image.h
    misc/Median.h
    misc/MetaObject.h
    misc/ObjectCache.h
    misc/ObjectManager.h
    misc/OptionsList.h
    misc/PBSettingsMacros.h
    misc/PVBlob.h
    misc/PackLambda.h
    misc/PixelTree.h
    misc/ProtectedProperty.h
    misc/ProximityGrid.h
    misc/RBSettings.h
    misc/ReverseAdapter.h
    misc/SampleInterpolator.h
    misc/SpriteMap.h
    misc/SpriteProperty.h
    misc/TaskQueue.h
    misc/ThreadManager.h
    misc/ThreadPool.h
    misc/ThreadedAnalysis.h
    misc/ThreadedAnalysis_impl.h
    misc/Timer.h
    misc/TooltipData.h
    misc/UnorderedVectorSet.h
    misc/bid.h
    misc/checked_casts.h
    misc/cnpy_wrapper.h
    misc/colors.h
    misc/create_struct.h
    misc/curve_discussion.h
    misc/custom_exceptions.h
    misc/date.h
    misc/default_settings.h
    misc/defines.h
    misc/derived_ptr.h
    misc/detail.h
    misc/fixed_string.h
    misc/format.h
    misc/frame_t.h
    misc/math.h
    misc/matharray.h
    misc/metastring.h
    misc/ocl.h
    misc/parse_parameter_lists.h
    misc/pretty.h
    misc/ranges.h
    misc/stacktrace.h
    misc/stringutils.h
    misc/useful_concepts.h
    misc/utilsexception.h
    misc/vec2.h
    misc/zipper.h
    file/CSVExport.h
    file/CSVReader.h
    file/DataFormat.h
    file/DataLocation.h
    file/Export.h
    file/Path.h
    file/PathArray.h
    file/ask_for_permission.h
    processing/Background.h
    processing/Brototype.h
    processing/CPULabeling.h
    processing/DLList.h
    processing/HLine.h
    processing/ListCache.h
    processing/LuminanceGrid.h
    processing/Node.h
    processing/PadImage.h
    processing/RawProcessing.h
    processing/Source.h
    processing/encoding.h
    video/AveragingAccumulator.h
    video/FFmpegVideoCapture.h
    video/GenericVideo.h
    video/Video.h
    video/VideoSource.h
    gui/ControlsAttributes.h
    gui/CornerFlags.h
    gui/CrossPlatform.h
    gui/Dispatcher.h
    gui/DrawBase.h
    gui/DrawCVBase.h
    gui/DrawHTMLBase.h
    gui/DrawObject.h
    gui/DrawSFBase.h
    gui/DrawStructure.h
    gui/DrawableCollection.h
    gui/DynamicGUI.h
    gui/DynamicVariable.h
    gui/Event.h
    gui/FileChooser.h
    gui/GLImpl.h
    gui/GUITaskQueue.h
    gui/Graph.h
    gui/GuiTypes.h
    gui/HttpClient.h
    gui/IMGUIBase.h
    gui/IatHook.h
    gui/LabeledField.h
    gui/ListAttributes.h
    gui/MacProgressBar.h
    gui/MetalImpl.h
    gui/ParseLayoutTypes.h
    gui/Passthrough.h
    gui/SFLoop.h
    gui/SVG.h
    gui/Section.h
    gui/Transform.h
    gui/darkmode.h
    gui/dyn/Action.h
    gui/dyn/CTimer.h
    gui/dyn/Context.h
    gui/dyn/ParseText.h
    gui/dyn/ResolveVariable.h
    gui/dyn/State.h
    gui/dyn/UnresolvedStringPattern.h
    gui/dyn/VarProps.h
    gui/dyn/binders.h
    gui/types/Basic.h
    gui/types/Button.h
    gui/types/Checkbox.h
    gui/types/Combobox.h
    gui/types/Drawable.h
    gui/types/Dropdown.h
    gui/types/Entangled.h
    gui/types/ErrorElement.h
    gui/types/HistOptions.h
    gui/types/Histogram.h
    gui/types/Layout.h
    gui/types/List.h
    gui/types/ListItemTypes.h
    gui/types/MiscShapes.h
    gui/types/PieChart.h
    gui/types/ScrollableList.h
    gui/types/Serializable.h
    gui/types/SettingsTooltip.h
    gui/types/SingletonObject.h
    gui/types/StaticText.h
    gui/types/Table.h
    gui/types/Textfield.h
    gui/types/Tooltip.h
    http/httpd.h
    modules/commons.exports.hpp
)

set(COMMONS_MISC_HEADERS
    misc/Base64.h
    misc/Blob.h
    misc/Buffers.h
    misc/CTCollection.h
    misc/CallbackManager.h
    misc/CircularGraph.h
    misc/CommandLine.h
    misc/CropOffsets.h
    misc/Deprecations.h
    misc/DisplayValue.h
    misc/EnumClass.h
    misc/FormatColor.h
    misc/GlobalSettings.h
    misc/Grid.h
    misc/IllegalVector.h
    misc/Image.h
    misc/Median.h
    misc/MetaObject.h
    misc/ObjectCache.h
    misc/ObjectManager.h
    misc/OptionsList.h
    misc/PBSettingsMacros.h
    misc/PVBlob.h
    misc/PackLambda.h
    misc/PixelTree.h
    misc/ProtectedProperty.h
    misc/ProximityGrid.h
    misc/RBSettings.h
    misc/ReverseAdapter.h
    misc/SampleInterpolator.h
    misc/SpriteMap.h
    misc/SpriteProperty.h
    misc/TaskQueue.h
    misc/ThreadManager.h
    misc/ThreadPool.h
    misc/ThreadedAnalysis.h
    misc/ThreadedAnalysis_impl.h
    misc/Timer.h
    misc/TooltipData.h
    misc/UnorderedVectorSet.h
    misc/bid.h
    misc/checked_casts.h
    misc/cnpy_wrapper.h
    misc/colors.h
    misc/create_struct.h
    misc/curve_discussion.h
    misc/custom_exceptions.h
    misc/date.h
    misc/default_settings.h
    misc/defines.h
    misc/derived_ptr.h
    misc/detail.h
    misc/fixed_string.h
    misc/format.h
    misc/frame_t.h
    misc/math.h
    misc/matharray.h
    misc/metastring.h
    misc/ocl.h
    misc/parse_parameter_lists.h
    misc/pretty.h
    misc/ranges.h
    misc/stacktrace.h
    misc/stringutils.h
    misc/useful_concepts.h
    misc/utilsexception.h
    misc/vec2.h
    misc/zipper.h
)

set(COMMONS_FILE_HEADERS
    file/CSVExport.h
    file/CSVReader.h
    file/DataFormat.h
    file/DataLocation.h
    file/Export.h
    file/Path.h
    file/PathArray.h
    file/ask_for_permission.h
)

set(COMMONS_PROCESSING_HEADERS
    processing/Background.h
    processing/Brototype.h
    processing/CPULabeling.h
    processing/DLList.h
    processing/HLine.h
    processing/ListCache.h
    processing/LuminanceGrid.h
    processing/Node.h
    processing/PadImage.h
    processing/RawProcessing.h
    processing/Source.h
    processing/encoding.h
)

set(COMMONS_VIDEO_HEADERS
    video/AveragingAccumulator.h
    video/FFmpegVideoCapture.h
    video/GenericVideo.h
    video/Video.h
    video/VideoSource.h
)

set(COMMONS_GUI_HEADERS
    gui/ControlsAttributes.h
    gui/CornerFlags.h
    gui/CrossPlatform.h
    gui/Dispatcher.h
    gui/DrawBase.h
    gui/DrawCVBase.h
    gui/DrawHTMLBase.h
    gui/DrawObject.h
    gui/DrawSFBase.h
    gui/DrawStructure.h
    gui/DrawableCollection.h
    gui/DynamicGUI.h
    gui/DynamicVariable.h
    gui/Event.h
    gui/FileChooser.h
    gui/GLImpl.h
    gui/GUITaskQueue.h
    gui/Graph.h
    gui/GuiTypes.h
    gui/HttpClient.h
    gui/IMGUIBase.h
    gui/IatHook.h
    gui/LabeledField.h
    gui/ListAttributes.h
    gui/MacProgressBar.h
    gui/MetalImpl.h
    gui/ParseLayoutTypes.h
    gui/Passthrough.h
    gui/SFLoop.h
    gui/SVG.h
    gui/Section.h
    gui/Transform.h
    gui/darkmode.h
    gui/types/Basic.h
    gui/types/Button.h
    gui/types/Checkbox.h
    gui/types/Combobox.h
    gui/types/Drawable.h
    gui/types/Dropdown.h
    gui/types/Entangled.h
    gui/types/ErrorElement.h
    gui/types/HistOptions.h
    gui/types/Histogram.h
    gui/types/Layout.h
    gui/types/List.h
    gui/types/ListItemTypes.h
    gui/types/MiscShapes.h
    gui/types/PieChart.h
    gui/types/ScrollableList.h
    gui/types/Serializable.h
    gui/types/SettingsTooltip.h
    gui/types/SingletonObject.h
    gui/types/StaticText.h
    gui/types/Table.h
    gui/types/Textfield.h
    gui/types/Tooltip.h
)

set(COMMONS_GUI_DYN_HEADERS
    gui/dyn/Action.h
    gui/dyn/CTimer.h
    gui/dyn/Context.h
    gui/dyn/ParseText.h
    gui/dyn/ResolveVariable.h
    gui/dyn/State.h
    gui/dyn/UnresolvedStringPattern.h
    gui/dyn/VarProps.h
    gui/dyn/binders.h
)

set(COMMONS_HTTP_HEADERS
    http/httpd.h
)

set(COMMONS_CPP_SOURCES
    types.cpp
    misc/Base64.cpp
    misc/Blob.cpp
    misc/Buffers.cpp
    misc/CallbackManager.cpp
    misc/CircularGraph.cpp
    misc/CommandLine.cpp
    misc/CropOffsets.cpp
    misc/Deprecations.cpp
    misc/GlobalSettings.cpp
    misc/Grid.cpp
    misc/Image.cpp
    misc/PVBlob.cpp
    misc/PixelTree.cpp
    misc/ProximityGrid.cpp
    misc/SpriteMap.cpp
    misc/SpriteProperty.cpp
    misc/ThreadManager.cpp
    misc/ThreadPool.cpp
    misc/Timer.cpp
    misc/TooltipData.cpp
    misc/bid.cpp
    misc/cnpy_wrapper.cpp
    misc/colors.cpp
    misc/curve_discussion.cpp
    misc/default_settings.cpp
    misc/derived_ptr.cpp
    misc/detail.cpp
    misc/format.cpp
    misc/metastring.cpp
    misc/ocl.cpp
    misc/pretty.cpp
    misc/stringutils.cpp
    misc/utilsexception.cpp
    misc/vec2.cpp
    file/CSVExport.cpp
    file/CSVReader.cpp
    file/DataFormat.cpp
    file/DataLocation.cpp
    file/Export.cpp
    file/Path.cpp
    file/PathArray.cpp
    processing/Background.cpp
    processing/Brototype.cpp
    processing/CPULabeling.cpp
    processing/DLList.cpp
    processing/ListCache.cpp
    processing/LuminanceGrid.cpp
    processing/PadImage.cpp
    processing/RawProcessing.cpp
    processing/Source.cpp
    video/AveragingAccumulator.cpp
    video/FFmpegVideoCapture.cpp
    video/GenericVideo.cpp
    video/Video.cpp
    video/VideoSource.cpp
    gui/ControlsAttributes.cpp
    gui/CornerFlags.cpp
    gui/DrawBase.cpp
    gui/DrawCVBase.cpp
    gui/DrawHTMLBase.cpp
    gui/DrawObject.cpp
    gui/DrawSFBase.cpp
    gui/DrawStructure.cpp
    gui/DrawableCollection.cpp
    gui/DynamicGUI.cpp
    gui/Event.cpp
    gui/FileChooser.cpp
    gui/GLImpl.cpp
    gui/Graph.cpp
    gui/GuiTypes.cpp
    gui/HttpClient.cpp
    gui/IMGUIBase.cpp
    gui/LabeledField.cpp
    gui/ParseLayoutTypes.cpp
    gui/SFLoop.cpp
    gui/SVG.cpp
    gui/Section.cpp
    gui/Transform.cpp
    gui/dyn/Action.cpp
    gui/dyn/Context.cpp
    gui/dyn/ParseText.cpp
    gui/dyn/ResolveVariable.cpp
    gui/dyn/State.cpp
    gui/dyn/UnresolvedStringPattern.cpp
    gui/dyn/VarProps.cpp
    gui/types/Basic.cpp
    gui/types/Button.cpp
    gui/types/Checkbox.cpp
    gui/types/Combobox.cpp
    gui/types/Drawable.cpp
    gui/types/Dropdown.cpp
    gui/types/Entangled.cpp
    gui/types/ErrorElement.cpp
    gui/types/Histogram.cpp
    gui/types/Layout.cpp
    gui/types/List.cpp
    gui/types/ListItemTypes.cpp
    gui/types/MiscShapes.cpp
    gui/types/PieChart.cpp
    gui/types/Serializable.cpp
    gui/types/SettingsTooltip.cpp
    gui/types/SingletonObject.cpp
    gui/types/StaticText.cpp
    gui/types/Table.cpp
    gui/types/Textfield.cpp
    gui/types/Tooltip.cpp
    http/httpd.cpp
)

set(COMMONS_MODULE_INTERFACE_UNITS
    modules/commons.cppm
    modules/commons.types.cppm
    modules/commons.misc.cppm
    modules/commons.file.cppm
    modules/commons.processing.cppm
    modules/commons.video.cppm
    modules/commons.gui.cppm
    modules/commons.gui.dyn.cppm
    modules/commons.http.cppm
)
