name: Update README

on:
  push:
    paths:
      - 'examples/test_gui.json'
      - 'examples/simple_gui.cpp'
      - '.github/workflows/update-readme.yml'
      - '.github/scripts/update-readme.py'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install PyYAML  # or any other dependencies you might need

    - name: Update README
      run: python .github/scripts/update-readme.py
      
    - name: Display changes
      run: |
        cat README.md
        git diff
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --cached --exit-code || echo "Changes detected"
        git diff --cached --exit-code || git commit -m "Automatically updated README.md"
        echo git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
    